### ISSUE TITLE
tested radoneye with older RD200

### ISSUE THREAD

**Issue by RLux21** [sormy/radoneye#1]
I am new to programming in Python. I installed radoneye on my raspberry pi 5 today. I have an older RD200 and ran into a few issues. The issues could certainly be due to me not knowing what I am doing. I wanted to share them with you as you wanted feedback from an older version 1 device. I am happy to work with you. I have included a file with my installation process as well as simple test results.
[Radoneye test on older RD200.pdf](https://github.com/sormy/radoneye/files/14436752/Radoneye.test.on.older.RD200.pdf)

**Comment by sormy** [comment]
Thanks for confirmation that list and status do work. What kind of phone do you have? I will need you to run official radoneye app and dump bluetooth stack packets. Does old RD200 beep on connection from app? Does app show a history? Does information on RD200 LCD screen match with output of status? What values do match and what do not?

**Comment by RLux21** [comment]
I have an iPhone.

**Comment by RLux21** [comment]
Artem Here is a more complete answer to your questions. - iPhone- The radon eye does beep when the app connects to it. - It does record and store data that can be downloaded as a file. - see screen shots.

**Comment by sormy** [comment]
And one more question. Do you have a device with macOS?

**Comment by sormy** [comment]
If you have iOS and macOS, then this is a a route: https://www.bluetooth.com/blog/a-new-way-to-debug-iosbluetooth-applications/?ref=guide.billsnyder.me

In short: install certificate on ios device, connect ios device to macOS, install xcode, download packet logger (part of Additional Tools for XCode), then run packet logger on macOS and sniff bluetooth stack on ios, run RadonEye app and see what is going on with bluetooth stack. Do a filtering based on BLE address, record a clear dump of connection to device from RadonEye. Notice when device is being connected, beep and click on history tab in app. This all should trigger command (set of bytes) to specific characteristic and there should be immediate response or response with callback with data. History has multiple callbacks. Record all that stuff and export from packet  logger to file and share with me. art.sormy@gmail.com If you could also note all exact values on RadonEye device screen like (current average, daily average, monthly average, uptime, counts (X/Y) and attach to dump, then we can guess where other missing parts are located.

**Comment by RLux21** [comment]
Artem Sounds like a plan. I have a Mac and will try this over the next few days.

**Comment by sormy** [comment]
Also, you can install iOS RadonEye app on modern macOS and sniff straight from macOS using the same packet logger.

**Comment by RLux21** [comment]
The Radoneye app for the Mac requires a Mac with an M1 or later chipset. I have a 2019 MacBook Pro, so no go for me.

**Comment by sormy** [comment]
Resolving, thanks for @RLux21 support we got full v1 support.
